### ISSUE TITLE
【請求】Gitkraken 8.8.0 支援

### ISSUE THREAD

**Issue by EvanHsieh0415** [rogeraabbccdd/GitKraken-zh-tw#10]
RT，目前更新到8.8.0後未顯示Language選項
![image](https://user-images.githubusercontent.com/74277414/189109114-cdf8b173-7a37-4080-82fc-0b2d15d1861d.png)

**Comment by rogeraabbccdd** [comment]
最近在忙其他的東西都沒用 GitKraken，所以沒注意到有更新
GitKraken 在 9/7 時發布了 8.9.0 更新
所以我跳過 8.8.0 直接支援 8.9.0 了

**Comment by EvanHsieh0415** [comment]
收到，感謝大大
