### ISSUE TITLE
Release 建議翻譯為【發行】。

### ISSUE THREAD

**Issue by hwhsu1231** [rogeraabbccdd/GitKraken-zh-tw#14]
### 建議

* **英文字串:** Release
* **當前翻譯:** 發佈
* **建議翻譯:** 發行

雖然【發佈】和【發行】的意思滿相近的，但是我個人傾向於將它們分別翻譯為:

* Release: 發行
* Publish: 發佈

這樣一來，我們就比較容易將【發行/發佈】翻譯回對應的英文【Release/Publish】。

例如:

* 訂閱/發佈: Subscribe/Publish
* 偵錯/發行: Debug/Release

**Comment by EvanHsieh0415** [comment]
同意

**Comment by rogeraabbccdd** [comment]
感謝，已修改
