### ISSUE TITLE
Rebase 建議翻譯為【重定基底】。

### ISSUE THREAD

**Issue by hwhsu1231** [rogeraabbccdd/GitKraken-zh-tw#15]
### 建議

* **英文字串:** Rebase
* **當前翻譯:** 變基
* **建議翻譯:** 重定基底

我在 idea-l10n-zht 中也這麼建議。主要是參考微軟的 VSCode。

* https://github.com/bluelovers/idea-l10n-zht/issues/70

**Comment by rogeraabbccdd** [comment]
感謝，已修改
