### ISSUE TITLE
Release Note 建議翻譯為【發行備註】。

### ISSUE THREAD

**Issue by hwhsu1231** [rogeraabbccdd/GitKraken-zh-tw#16]
### 建議

* **英文字串:** Release Note
* **當前翻譯:** 版本資訊
* **建議翻譯:** 發行備註

具體解釋可以參考【風吹草動】網誌作者 @zerng07 的【[這篇文章](http://breezymove.blogspot.com/2023/01/release-note-candidate.html)】。

除此之外，如果將【Release Note】翻譯為【版本資訊】的話，當我們要將中文翻譯回英文時，有可能會翻譯成【Version Information】。畢竟【Version】一般翻譯為【版本】，而【Information】一般翻譯為【資訊】。為了避免翻過去再翻回來後，變成完全不同的詞，我建議將【Release Note】翻譯為【發行備註】。

### 版本

* **Gitkraken-zh-tw:** `9.0.1`

**Comment by rogeraabbccdd** [comment]
感謝，已修改
