### ISSUE TITLE
Preferences 建議翻譯為【偏好設定】。

### ISSUE THREAD

**Issue by hwhsu1231** [rogeraabbccdd/GitKraken-zh-tw#17]
### 建議

* **英文字串:** Preferences
* **當前翻譯:** 喜好設定
* **建議翻譯:** 偏好設定

事實上，無論是【偏好】還是【喜好】都可以翻譯為【Preferneces】。但是因為【偏好】的發音與【Preferences】一樣都是【P】開頭，再加上就我的觀察目前除了微軟平台以外的其他繁體中文(台灣)介面幾乎都採用【偏好】，所以我建議將【Preferences】翻譯為【偏好設定】。

相關範例參考: https://github.com/microsoft/vscode-loc/issues/1259#issuecomment-1420671085

### 版本

* **Gitkraken-zh-tw:** `9.1.1`

**Comment by rogeraabbccdd** [comment]
感謝，已修改
