### ISSUE TITLE
View 建議統一翻譯為【檢視】。

### ISSUE THREAD

**Issue by hwhsu1231** [rogeraabbccdd/GitKraken-zh-tw#18]
### 建議

* **英文字串:** View
* **當前翻譯:** 檢視、查看
* **建議翻譯:** 檢視

其實無論是【檢視】還是【查看】都可以翻譯為【View】。但我的想法是，如果台灣這邊選擇將【View】翻譯為【檢視】的話，那麼就盡量在翻譯上採用同一個術語。類似的案例像是，版本控制中的【Change】其實是可以翻譯為【變更、更改、修改...等】同義詞，但是 zh-TW 語系中目前翻譯為【變更】是佔大多數的，那麼就盡量統一使用這個翻譯（在版本控制的領域中）。

從 [vscode-loc](https://github.com/microsoft/vscode-loc) 提供的範例做參考的話：

* zh-cn: 將 View 翻譯為【查看】。
* zh-tw: 將 View 翻譯為【檢視】。

![image](https://user-images.githubusercontent.com/71438617/223691716-c05de96f-f5be-4ece-bdd8-6a851f46ab68.png)

### 版本

* **Gitkraken-zh-tw:** `9.2.0`

**Comment by rogeraabbccdd** [comment]
感謝，已修改
