### ISSUE TITLE
Repository 建議統一翻譯為【儲存庫】。

### ISSUE THREAD

**Issue by hwhsu1231** [rogeraabbccdd/GitKraken-zh-tw#19]
### 建議

* **英文字串:** Repository
* **當前翻譯:** 儲存庫、存儲庫
* **建議翻譯:** 儲存庫

同 #18 中提到的想法。

### 版本

* **Gitkraken-zh-tw:** `9.2.0`

**Comment by rogeraabbccdd** [comment]
感謝，已修改
