### ISSUE TITLE
7.5.2 找不到Mac `/Applications/GitKraken.app/Contents/Resources/app/src/strings.json`

### ISSUE THREAD

**Issue by WingCH** [rogeraabbccdd/GitKraken-zh-tw#2]
![image](https://user-images.githubusercontent.com/19588517/109736029-b6941600-7bfe-11eb-9045-2127e4ad4278.png)

**Comment by rogeraabbccdd** [comment]
我沒有 macOS 裝置，我也不知道 string.json 的實際位置  
README 上的路徑是從別的翻譯 README 複製來的

**Comment by rogeraabbccdd** [comment]
mac 的路徑為 `/Applications/GitKraken.app/Contents/Resources/app.asar.unpacked/src/strings.json`  
已更新至 README.md  https://github.com/rogeraabbccdd/GitKraken-zh-tw/commit/cdf20d747327b10dde5244030476b718eff9a1c7
