### ISSUE TITLE
7.5.2:以取代strings.json檔案，但是GitKraken沒有中文化

### ISSUE THREAD

**Issue by a127521421** [rogeraabbccdd/GitKraken-zh-tw#6]
本人用了三台電腦做測試，三台都沒有中文化。
![擷取](https://user-images.githubusercontent.com/26712208/110792420-54967900-82ae-11eb-8595-8bdfb1e18ef6.PNG)

**Comment by rogeraabbccdd** [comment]
問題已解決，請重新下載翻譯檔取代後重開
