### ISSUE TITLE
8.3.2 Pre 1 Realse 檔案錯誤

### ISSUE THREAD

**Issue by shuwn** [rogeraabbccdd/GitKraken-zh-tw#7]
Release 上傳到錯誤的檔案，變成英文檔，麻煩請再更新，謝謝！

<img width="1167" alt="Image_20220317_223844" src="https://user-images.githubusercontent.com/20023822/158829925-75a0fe6d-3995-4f7b-b4f1-ab750394054e.png">

**Comment by rogeraabbccdd** [comment]
抱歉現在才看到，已更新
